### ISSUE TITLE
Add JavaScript example of passthrough

### ISSUE THREAD

**Issue by rain1** [imposter-project/examples#1]
https://github.com/imposter-project/examples/blob/main/rest/passthrough-upstream/imposter-config.yaml

```yaml
plugin: rest

upstreams:
  example:
    url: https://example.com

resources:
  # forward requests to upstream
  - path: /*
    passthrough: example

  # mock a response
  - path: /mock
    response:
      statusCode: 200
      content: "Hello from a mock"
      headers:
        Content-Type: text/plain
```

Is there a way to do this in JavaScript? If yes would it possible to add this example? I couldn't figure myself how to do `passthrough` part.
